Args = -H:+ReportExceptionStackTraces \
       --initialize-at-run-time=io.ktor \
       --initialize-at-run-time=kotlinx.coroutines \
       --initialize-at-build-time=kotlin.DeprecationLevel \
       -march=compatibility \
       -H:+AddAllCharsets \
       -Ob
